import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { ThemeLanguageProvider } from "./components/ThemeLanguageProvider";
import LayoutContent from "./components/LayoutContent";

const notoSans = Noto_Sans({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.className} min-h-screen flex flex-col`}>
        <ThemeLanguageProvider>
          <LayoutContent>{children}</LayoutContent>
        </ThemeLanguageProvider>
      </body>
    </html>
  );
}
