import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import AudioPlayer from "./components/AudioPlayer";

const notoSans = Noto_Sans({
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <div className="relative bg-[url('/Images/Background/background.gif')] bg-cover bg-center">
          <main className="relative z-10">
            <div className="relative z-10">
              {children}
            </div>
          </main>
          <AudioPlayer />
        </div>
      </body>
    </html>
  );
}
